# Generated by Django 5.0.6 on 2024-05-19 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('categoria',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=150, verbose_name='Produto')),
                ('descricao', models.CharField(max_length=250, null=True)),
                ('codigo_barra', models.CharField(max_length=50, null=True)),
                ('estoque_min', models.IntegerField(null=True)),
                ('estoque_max', models.IntegerField(null=True)),
                ('estoque_atual', models.IntegerField(null=True)),
                ('valor_custo', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.categoria')),
            ],
            options={
                'ordering': ('name_product',),
            },
        ),
    ]
