# Generated by Django 5.0.6 on 2024-05-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
