# Generated by Django 5.0.6 on 2024-05-24 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, unique=True)),
                ('quantidade', models.IntegerField(null=True)),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.product')),
            ],
        ),
    ]
