# Generated by Django 5.0.6 on 2024-05-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_saidaestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaestoque',
            name='saldo',
            field=models.IntegerField(null=True),
        ),
    ]
