# Generated by Django 5.0.6 on 2024-05-24 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_saidaestoque_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, unique=True)),
                ('quantidade', models.IntegerField(null=True)),
                ('saldo', models.IntegerField(default=0, null=True)),
                ('data', models.DateField(auto_now_add=True, null=True)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.product')),
            ],
        ),
    ]
