# Generated by Django 5.0.6 on 2024-05-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_entradaestoque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name_product',), 'verbose_name': 'Produto', 'verbose_name_plural': 'PRODUTOS'},
        ),
        migrations.AlterField(
            model_name='product',
            name='estoque_atual',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
