# Generated by Django 5.0.6 on 2024-05-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_alter_product_options_alter_product_estoque_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaestoque',
            name='Venda | Sim ou Não: ',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
