# Generated by Django 5.0.6 on 2024-05-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_alter_product_options_alter_product_estoque_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaestoque',
            name='status',
            field=models.BooleanField(default=1, verbose_name='Venda'),
        ),
    ]
