# Generated by Django 5.0.6 on 2024-05-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_saidaestoque_venda_sim_ou_não_'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saidaestoque',
            name='Venda | Sim ou Não: ',
        ),
        migrations.AddField(
            model_name='saidaestoque',
            name='status',
            field=models.BooleanField(default=1, verbose_name='Venda'),
            preserve_default=False,
        ),
    ]
