# Generated by Django 5.0.6 on 2024-05-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_remove_saidaestoque_venda_sim_ou_não__and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaestoque',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='saidaestoque',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
