# Generated by Django 5.0.6 on 2024-05-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_saidaestoque_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaestoque',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='PREÇO'),
        ),
        migrations.AlterField(
            model_name='saidaestoque',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
