# Generated by Django 5.0.6 on 2024-05-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_saidaestoque_preco_alter_saidaestoque_subtotal'),
        ('estoque', '0013_saidaestoque_preco_saidaestoque_subtotal'),
    ]

    operations = [
    ]
