# Generated by Django 5.0.6 on 2024-05-21 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_cliente_endereco2'),
        ('estoque', '0003_cliente'),
        ('servico', '0004_ordemservicoproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservicoproduto',
            name='produto_servico',
        ),
        migrations.AlterModelOptions(
            name='ordemservico',
            options={},
        ),
        migrations.RemoveField(
            model_name='servico',
            name='observacao',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Serviço'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.product'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servico.servico'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='cliente.cliente', verbose_name='cliente'),
        ),
        migrations.DeleteModel(
            name='OrdemServicoItem',
        ),
        migrations.DeleteModel(
            name='OrdemServicoProduto',
        ),
    ]
