# Generated by Django 5.0.6 on 2024-05-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0005_remove_ordemservicoproduto_produto_servico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observacção'),
        ),
    ]
