# Generated by Django 5.0.6 on 2024-05-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0007_ordemservico_valor_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='valor_lucro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Lucro'),
        ),
    ]
