# Generated by Django 5.0.6 on 2024-05-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0008_ordemservico_valor_lucro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='valor_produto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='valor Produto'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Valor total'),
        ),
    ]
