# Generated by Django 5.0.6 on 2024-05-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0012_remove_ordemservico_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='valor_custo',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='valor_lucro',
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
