# Generated by Django 5.0.6 on 2024-05-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0014_alter_ordemservico_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data do Serviço'),
        ),
    ]
