# Generated by Django 5.0.6 on 2024-06-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0016_ordemservicofim'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Valor total'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_custo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Valor Custo'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_lucro',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Valor Lucro'),
        ),
        migrations.DeleteModel(
            name='OrdemServicoFim',
        ),
    ]
