# Generated by Django 5.0.6 on 2024-06-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0017_ordemservico_valor_ordemservico_valor_custo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_termino',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data do Serviço'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='solucao',
            field=models.TextField(blank=True, null=True, verbose_name='Solução'),
        ),
    ]
