# Generated by Django 5.0.6 on 2024-06-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0018_ordemservico_data_termino_ordemservico_solucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data_termino',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Término'),
        ),
    ]
