# Generated by Django 5.0.6 on 2024-05-22 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0002_remove_entradaestoque_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'FORNECEDOR',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'MATERIAL',
            },
        ),
        migrations.RemoveField(
            model_name='saidaestoque',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='saidaestoque',
            name='os',
        ),
        migrations.RemoveField(
            model_name='saidaestoque',
            name='produto',
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_fiscal', models.CharField(max_length=10)),
                ('data', models.DateField()),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacao.fornecedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'COMPRAS',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='PREÇO')),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='QUANTIDADE')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacao.compra')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacao.material')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'PRODUTOS',
            },
        ),
        migrations.DeleteModel(
            name='EntradaEstoque',
        ),
        migrations.DeleteModel(
            name='SaidaEstoque',
        ),
    ]
