# Generated by Django 5.0.6 on 2024-05-22 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_cliente_endereco2'),
        ('estoque', '0004_delete_cliente'),
        ('servico', '0007_ordemservico_valor_custo'),
        ('transacao', '0003_fornecedor_material_remove_saidaestoque_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='material',
        ),
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.product')),
            ],
        ),
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente')),
                ('os', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servico.ordemservico')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
