# Generated by Django 5.0.6 on 2024-05-23 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_delete_cliente'),
        ('transacao', '0005_fornecedor_material_remove_saidaestoque_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.product'),
        ),
    ]
