# Generated by Django 5.0.6 on 2024-05-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0006_alter_produto_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
