# Generated by Django 5.0.6 on 2024-05-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0009_remove_compra_valor_compra_alter_compra_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='valor_compra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
