# Generated by Django 5.0.6 on 2024-05-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0010_compra_valor_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='entrada',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
