# Generated by Django 5.0.6 on 2024-05-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0011_produto_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='entrada',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
