# Generated by Django 5.0.6 on 2024-05-25 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_cliente_endereco2'),
        ('estoque', '0009_entradaestoque'),
        ('transacao', '0013_remove_produto_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_fiscal', models.CharField(max_length=10)),
                ('data', models.DateField()),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'VENDAS',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='PREÇO')),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='QUANTIDADE')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.product')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacao.venda')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'PRODUTOS',
            },
        ),
    ]
