# Generated by Django 5.0.6 on 2024-05-25 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0014_venda_produtovenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='fornecedor',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='valor_compra',
            new_name='valor_venda',
        ),
    ]
